---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ccloud

  broker-1:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-1
    container_name: broker-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:9092
    networks:
      - ccloud
  
  broker-2:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-2
    container_name: broker-2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:9092
    networks:
      - ccloud

  broker-3:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-3
    container_name: broker-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-3:9092
    networks:
      - ccloud

  kafka-proxy:
    image: grepplabs/kafka-proxy
    hostname: kafka-proxy
    container_name: kafka-proxy
    command: server --bootstrap-server-mapping=broker-1:9092,0.0.0.0:9092,kafka-proxy:9092 --bootstrap-server-mapping=broker-2:9092,0.0.0.0:9093,kafka-proxy:9092 --bootstrap-server-mapping=broker-3:9092,0.0.0.0:9094,kafka-proxy:9092
    depends_on:
      - broker-1
      - broker-2
      - broker-3
    networks:
      - ccloud
      - onpremise

  haproxy-1:
    image: haproxy:2.0.7
    hostname: haproxy-1
    container_name: haproxy-1
    depends_on:
      - broker-1
    volumes:
     - $PWD/haproxy-1.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - ccloud
      - onpremise

  haproxy-2:
    image: haproxy:2.0.7
    hostname: haproxy-2
    container_name: haproxy-2
    depends_on:
      - broker-2
    volumes:
     - $PWD/haproxy-2.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - ccloud
      - onpremise

  haproxy-3:
    image: haproxy:2.0.7
    hostname: haproxy-3
    container_name: haproxy-3
    depends_on:
      - broker-3
    volumes:
     - $PWD/haproxy-1.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - ccloud
      - onpremise

  kafka-client:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    container_name: kafka-client
    entrypoint: /bin/sh -c "sleep 10000000"
    depends_on:
      - kafka-proxy
      - haproxy-1
      - haproxy-2
      - haproxy-3
    networks:
      - onpremise

networks:
    ccloud:
    onpremise:
        